name: WE_ALL_CREATE
favicon: null
layout_spectrum: 0.45671224291436374
typography_spectrum: 0.6663981743622571
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.125
  lightness: 0.4375
  saturation: 0.8125
  rhythmicContrast: 0.13076342060230672
purpose: []
